output: /Users/ryancampbell/Documents/Games/veeneck.github.io/SpeakerBox
readme_path: /Users/ryancampbell/Documents/Games/SpeakerBox/README.md
author_name: "Ryan Campbell"
author_url: "http://battleofbrothers.com"
hide_documentation_coverage: yes
min_acl: public
github_url: "https://github.com/veeneck/SpeakerBox"
root_url: "http://veeneck.github.io/SpeakerBox"
module_name: SpeakerBox
skip_undocumented: yes
